<?php
namespace App\Plugins\Gamification\database\seeds;
use Illuminate\Database\Seeder;
use DB;

class GaBadgesTableSeeder extends Seeder
{

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		$created_at = date('Y-d-m H:m:i');

		\DB::table('ga_badges')->delete();
		
		\DB::table('ga_badges')->insert(array (
			0 => 
			array (
				'id' => '3',
				'title' => 'Atendimento nota 10',
				'description' => 'Este distintivo é atribuído aos atendentes que atingem 10 pontos',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '4',
				'type_id' => '1',
				'icon_css' => NULL,
				'priority' => '5',
				'credits' => '0',
				'xp' => '0',
				'price' => '10',
				'notification' => 'Atingiu a marca de 10 pontos.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '0',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			1 => 
			array (
				'id' => '4',
				'title' => 'Atendimento nota 100',
				'description' => 'Este distintivo é atribuído aos atendentes que atingem 100 pontos',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '4',
				'type_id' => '1',
				'icon_css' => NULL,
				'priority' => '4',
				'credits' => '0',
				'xp' => '0',
				'price' => '100',
				'notification' => 'Este distintivo é atribuído aos atendentes que atingem 10 pontos',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '0',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			2 => 
			array (
				'id' => '5',
				'title' => 'Atendimento nota 1000',
				'description' => 'Este distintivo é atribuído aos atendentes que atingem 10 pontos',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '4',
				'type_id' => '1',
				'icon_css' => NULL,
				'priority' => '0',
				'credits' => '0',
				'xp' => '0',
				'price' => '1000',
				'notification' => 'Atingiu a marca de 1000 pontos.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '0',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			3 => 
			array (
				'id' => '6',
				'title' => 'Nível C',
				'description' => 'Primeiro nível a ser atingido por usuários do sistema. Para tanto o usuário deve atingir 1000 pontos, no entanto, ao atingir o nível este ganhará 100 pontos de bônus.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '7',
				'type_id' => '2',
				'icon_css' => NULL,
				'priority' => '1',
				'credits' => '100',
				'xp' => '0',
				'price' => '1000',
				'notification' => 'Você atingiu o Nível C, ganhou 100 pontos de bônus.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '0',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			4 => 
			array (
				'id' => '7',
				'title' => 'Nível B',
				'description' => 'Primeiro nível a ser atingido por usuários do sistema. Para tanto o usuário deve atingir 10000 pontos, no entanto, ao atingir o nível este ganhará 1000 pontos de bônus.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '7',
				'type_id' => '2',
				'icon_css' => NULL,
				'priority' => '1',
				'credits' => '1000',
				'xp' => '0',
				'price' => '10000',
				'notification' => 'Parabéns você atingiu o Nível B e ganhará 1000 pontos de bônus.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '0',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			5 => 
			array (
				'id' => '8',
				'title' => 'Nível A',
				'description' => 'Maior nível a ser atingido por usuários do sistema. Para tanto o usuário deve atingir 100000 pontos, no entanto, ao atingir o nível este ganhará 100 pontos de bônus.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '7',
				'type_id' => '2',
				'icon_css' => NULL,
				'priority' => '0',
				'credits' => '10000',
				'xp' => '0',
				'price' => '100000',
				'notification' => 'Parabéns você atingiu o nível máximo do Tikiri. Será premiado com um bônus de 10.000 para usar como quiser.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '0',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			6 => 
			array (
				'id' => '14',
				'title' => 'Recebeu uma estrela na avaliação do atendimento',
				'description' => 'Esta pontuação o agente recebe sempre que o atendimento for avaliado.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '8',
				'type_id' => '3',
				'icon_css' => NULL,
				'priority' => '5',
				'credits' => '0',
				'xp' => '1',
				'price' => '0',
				'notification' => 'Parabéns você recebeu uma estrela na avaliação do atendimento que você fez.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '0',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			7 => 
			array (
				'id' => '15',
				'title' => 'Recebeu 02 estrelas na avaliação do atendimento',
				'description' => 'Esta pontuação o agente recebe sempre que o atendimento for avaliado.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '8',
				'type_id' => '3',
				'icon_css' => NULL,
				'priority' => '4',
				'credits' => '0',
				'xp' => '5',
				'price' => '0',
				'notification' => 'Parabéns você recebeu uma estrela na avaliação do atendimento que você fez e, com isso, acumulou [value] pontos.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '0',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			8 => 
			array (
				'id' => '16',
				'title' => 'Recebeu 03 estrelas na avaliação do atendimento',
				'description' => 'Esta pontuação o agente recebe sempre que o atendimento for avaliado.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '8',
				'type_id' => '3',
				'icon_css' => NULL,
				'priority' => '3',
				'credits' => '0',
				'xp' => '10',
				'price' => '0',
				'notification' => 'Parabéns você recebeu uma estrela na avaliação do atendimento que você fez e, com isso, acumulou [value] pontos.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '0',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			9 => 
			array (
				'id' => '17',
				'title' => 'Recebeu 04 estrelas na avaliação do atendimento',
				'description' => 'Esta pontuação o agente recebe sempre que o atendimento for avaliado.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '8',
				'type_id' => '3',
				'icon_css' => NULL,
				'priority' => '2',
				'credits' => '0',
				'xp' => '20',
				'price' => '0',
				'notification' => 'Parabéns você recebeu uma estrela na avaliação do atendimento que você fez e, com isso, acumulou [value] pontos.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '0',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			10 => 
			array (
				'id' => '18',
				'title' => 'Recebeu 05 estrelas na avaliação do atendimento',
				'description' => 'Esta pontuação o agente recebe sempre que o atendimento for avaliado.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '8',
				'type_id' => '3',
				'icon_css' => NULL,
				'priority' => '4',
				'credits' => '0',
				'xp' => '50',
				'price' => '0',
				'notification' => 'Parabéns você recebeu uma estrela na avaliação do atendimento que você fez e, com isso, acumulou [value] pontos.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '0',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			11 => 
			array (
				'id' => '19',
				'title' => 'Abriu um chamado',
				'description' => 'Esta pontuação será atribuída sempre que um chamado for aberto pelo sistema',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '9',
				'type_id' => '3',
				'icon_css' => NULL,
				'priority' => '6',
				'credits' => '0',
				'xp' => '5',
				'price' => '0',
				'notification' => 'Parabéns, você abriu um chamado pelo sistema, ganhou [value] pontos.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '0',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			12 => 
			array (
				'id' => '20',
				'title' => 'Compartilhamento de Conhecimento',
				'description' => 'Sempre que algo for postado na base de conhecimento esta pontuação será atribuída.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '10',
				'type_id' => '3',
				'icon_css' => NULL,
				'priority' => '4',
				'credits' => '0',
				'xp' => '20',
				'price' => '0',
				'notification' => 'Parabéns você compartilhou conhecimento na nossa Base de Conhecimento, ganhou [value] pontos.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '0',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			13 => 
			array (
				'id' => '21',
				'title' => '[100] Bônus por serviços não controlados pelo Tikiri',
				'description' => 'Este é um bônus controlado diretamente pela chefia.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '6',
				'type_id' => '4',
				'icon_css' => NULL,
				'priority' => '3',
				'credits' => '100',
				'xp' => '0',
				'price' => '0',
				'notification' => 'Parabéns, você recebeu um bônus de [value].',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '0',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			14 => 
			array (
				'id' => '24',
				'title' => 'Um turno de folga',
				'description' => 'O usuário terá direito a um dia de folga ao atingir os pontos mostrados no campo preço',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '5',
				'type_id' => '5',
				'icon_css' => NULL,
				'priority' => '1',
				'credits' => '0',
				'xp' => '0',
				'price' => '5000',
				'notification' => 'Você adquiriu a recompensa e utilizou [value] pontos..',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '1',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			15 => 
			array (
				'id' => '25',
				'title' => 'Recebeu 01 estrela na avaliação do contéudo que você postou',
				'description' => 'Esta pontuação o agente recebe sempre que o contéudo for avaliado.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '8',
				'type_id' => '3',
				'icon_css' => NULL,
				'priority' => '5',
				'credits' => '0',
				'xp' => '1',
				'price' => '0',
				'notification' => 'Parabéns você recebeu uma estrela na avaliação do conteúdo que postou, com isso, acumulou [value] pontos.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '1',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			16 => 
			array (
				'id' => '26',
				'title' => 'Recebeu 02 estrelas na avaliação do contéudo que você postou',
				'description' => 'Esta pontuação o agente recebe sempre que o contéudo for avaliado.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '8',
				'type_id' => '3',
				'icon_css' => NULL,
				'priority' => '5',
				'credits' => '0',
				'xp' => '5',
				'price' => '0',
				'notification' => 'Parabéns você recebeu 02 estrelas na avaliação do conteúdo que postou, com isso, acumulou [value] pontos.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '1',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			17 => 
			array (
				'id' => '27',
				'title' => 'Recebeu 03 estrelas na avaliação do contéudo que você postou',
				'description' => 'Esta pontuação o agente recebe sempre que o contéudo for avaliado.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '8',
				'type_id' => '3',
				'icon_css' => NULL,
				'priority' => '5',
				'credits' => '0',
				'xp' => '10',
				'price' => '0',
				'notification' => 'Parabéns você recebeu 03 estrelas na avaliação do conteúdo que postou, com isso, acumulou [value] pontos.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '1',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			18 => 
			array (
				'id' => '28',
				'title' => 'Recebeu 04 estrelas na avaliação do contéudo que você postou',
				'description' => 'Esta pontuação o agente recebe sempre que o contéudo for avaliado.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '8',
				'type_id' => '3',
				'icon_css' => NULL,
				'priority' => '5',
				'credits' => '0',
				'xp' => '20',
				'price' => '0',
				'notification' => 'Parabéns você recebeu 04 estrelas na avaliação do conteúdo que postou, com isso, acumulou [value] pontos.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '1',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
			19 => 
			array (
				'id' => '29',
				'title' => 'Recebeu 05 estrelas na avaliação do contéudo que você postou',
				'description' => 'Esta pontuação o agente recebe sempre que o contéudo for avaliado.',
				'icon' => NULL,
				'icon_sm' => NULL,
				'icon_lg' => NULL,
				'category_id' => '8',
				'type_id' => '3',
				'icon_css' => NULL,
				'priority' => '5',
				'credits' => '0',
				'xp' => '50',
				'price' => '0',
				'notification' => 'Parabéns você recebeu 5 estrelas na avaliação do conteúdo que postou, com isso, acumulou [value] pontos.',
				'isdeduct' => '0',
				'ilevel' => '0',
				'ishide' => '0',
				'ismultiple' => '1',
				'isactive' => '1',
				'created_at' => $created_at,
				'updated_at' => $created_at,
			),
		));
		
		
	}
}
