TRUNCATE table templates;


INSERT INTO tikiri2023.templates (name,variable,`type`,subject,message,description,set_id,created_at,updated_at) VALUES
	 ('Este modelo é para enviar aviso ao agente quando o ticket for atribuído a ele','0',1,'','<div>Olá {!!$ticket_agent_name!!},<br /><br />< b>Número do bilhete:</b> {!!$ticket_number!!}<br />Foi atribuído a você por {!!$ticket_assigner!!} <br /> Verifique e responda no bilhete.<br / > Link: {!!$ticket_link!!}<br /><br />Obrigado<br />Atenciosamente,<br /> {!!$system_from!!}</div>','',1,'2016-12-12 23:19:50','2016-12-12 23:19:50'),
	 ('Este modelo é para enviar aviso ao cliente com link do ticket para verificar o ticket sem fazer login no sistema','1',2,'Verifique seu ticket','<div>Olá {!!$user!!},< br /><br />Clique no link abaixo para visualizar o ticket solicitado<br /> {!!$ticket_link_with_number!!}<br /><br />Atenciosamente,<br /> {!!$system_from!! }</div>','',1,'2016-12-12 23:19:50','2016-12-12 23:19:50'),
	 ('Este modelo é para enviar aviso ao cliente quando o status do ticket for alterado para fechado','0',3,'','<div>Olá,<br /><br />Esta mensagem é referente ao ID do seu ticket {!!$ticket_number!!}. Estamos alterando o status deste ticket para "Fechado", pois o problema parece estar resolvido.<br /><br />Obrigado<br />Atenciosamente,<br /> {!!$system_from!!}</div>','',1,'2016-12-12 23:19:50','2016-12-12 23:19:50'),
	 ('Este modelo é para enviar aviso ao cliente sobre a criação bem-sucedida do ticket','0',4,'','<div><span>Olá {!!$user!!}<br><br><span>Obrigado por entrar em contato conosco. Esta é uma resposta automática confirmando o recebimento do seu ticket. Nossa equipe entrará em contato com você o mais breve possível. Ao responder, certifique-se de que o ID do ticket seja mantido no assunto para que possamos rastrear suas respostas.<br><br></span><span><b>ID do ticket:</b> {!!$ticket_number!!}<br><br> </span><span> {!!$department_sign!!}<br></span>Você pode verificar o status ou atualizar este ticket on-line em: {!!$system_link!!}</span></div>','',1,'2016-12-12 23:19:51','2023-12-09 01:59:55'),
	 ('Este modelo é para enviar aviso ao agente sobre a criação de um novo ticket','0',5,'','<div>Olá {!!$ticket_agent_name!!},<br><br>Novo ticket {!!$ticket_number!!}criado!<br><br><b>De</b><b>:</b> {!!$ticket_client_name!!} <br><b>E-mail:</b> {!!$ticket_client_email!!}<br><br> {!!$content!!}<br><br>Atenciosamente,<br> {!!$system_from!!}</div>','',1,'2016-12-12 23:19:51','2023-12-09 02:01:15'),
	 ('Este modelo é para enviar aviso ao cliente sobre novo ticket criado pelo agente em nome do cliente','0',6,'','<div> {!!$content!!}<br /><br / > {!!$agent_sign!!}<br /><br />Você pode verificar o status ou atualizar este ticket on-line em: {!!$system_link!!}</div>','',1,'2016-12-12 23:19:51','2016-12-12 23:19:51'),
	 ('Este modelo é para enviar aviso ao cliente sobre novo registro durante a criação de um novo ticket para clientes não registrados','1',7,'Confirmação de registro','<p>Olá {!!$user!!},</ p><p>Este e-mail é uma confirmação de que você está registrado em nosso suporte técnico.</p><p><b>E-mail registrado:</b> {!!$email_address!!}</p><p> <b>Senha:</b> {!!$user_password!!}</p><p>Você pode visitar o suporte técnico para navegar pelos artigos e entrar em contato conosco a qualquer momento: {!!$system_link!!}</p ><p>Obrigado.</p><p>Atenciosamente,</p><p> {!!$system_from!!}</p>','',1,'2016-12-12 23:19:51','2016-12-12 23:19:51'),
	 ('Este modelo é para enviar aviso a qualquer usuário sobre a opção de redefinição de senha','1',8,'Redefinir sua senha','Olá {!!$user!!},<br /><br />Você perguntou para redefinir sua senha. Para fazer isso, clique neste link:<br /><br /> {!!$password_reset_link!!}<br /><br />Isso permitirá que você altere sua senha para algo novo. Se você não pediu isso, não se preocupe, manteremos sua senha segura.<br /><br />Obrigado.<br /><br />Atenciosamente,<br /> {!!$system_from!!}','',1,'2016-12-12 23:19:51','2016-12-12 23:19:51'),
	 ('Este modelo é para enviar aviso ao cliente quando uma resposta for feita ao seu ticket','0',9,'','<span></span><div><span></span><p> {!!$content!!}<br></p><p> {!!$agent_sign!!}</p><p><b>ID do ticket:</b> {!!$ticket_number!!}</p></div>','',1,'2016-12-12 23:19:51','2023-12-09 02:05:27'),
	 ('Este modelo é para enviar aviso ao agente quando a resposta do ticket é feita pelo cliente em um ticket','0',10,'','<div>Olá {!!$ticket_agent_name!!},<br><br>Uma resposta foi feita ao ticket {!!$ticket_number!!}<br><b><br></b><b>Nome: </b>{!!$ticket_client_name!!}<br><b>E-mail: </b>{!!$ticket_client_email!!}<br><b><br></b> {!!$content!!}<br><b><br></b>Atenciosamente,<br> {!!$system_from!!}</div>','',1,'2016-12-12 23:19:51','2023-12-09 02:05:57');
INSERT INTO tikiri2023.templates (name,variable,`type`,subject,message,description,set_id,created_at,updated_at) VALUES
	 ('Este modelo é para enviar aviso ao cliente sobre o link de confirmação de registro','1',11,'Verifique seu endereço de e-mail','<p>Olá {!!$user!!},</p><p> Este e-mail é uma confirmação de que você está registrado em nosso suporte técnico.</p><p><b>E-mail registrado:</b> {!!$email_address!!}</p><p>Clique abaixo link para ativar sua conta e fazer login no sistema {!!$password_reset_link!!}</p><p>Obrigado.</p><p>Atenciosamente,</p><p> {!!$system_from!!}</p>','',1,'2016-12-12 23:19:52','2016-12-12 23:19:52'),
	 ('Este modelo é para enviar aviso à equipe quando o ticket é atribuído à equipe','1',12,'Ticket atribuído','<div>Olá {!!$ticket_agent_name!!},<br><br><b>Número do bilhete</b>: {!!$ticket_number!!}<br><b>Foi atribuído à sua equipe</b>: {!!$team!!} por {!!$ticket_assigner!!}<br></div><div><br></div><div>Obrigado<br>Atenciosamente,<br>{!!$system_from!!}</div>','',1,'2016-12-12 23:19:52','2023-12-09 02:04:59'),
	 ('Este modelo é para enviar aviso ao cliente quando a senha for alterada','1',13,'Verifique seu endereço de e-mail','Olá {!!$user!!},<br /><br />Sua senha foi alterada com sucesso.Sua nova senha é: {!!$user_password!!}<br /><br />Obrigado.<br /><br />Atenciosamente,<br /> {!!$system_from!! }','',1,'2016-12-12 23:19:52','2016-12-12 23:19:52'),
	 ('Este modelo serve para notificar os usuários quando seus tickets forem mesclados.','1',14,'Seus tickets foram mesclados.','<p>Olá {!!$user!!},<br></p><p>Seus tickets com número de ticket {!!$merged_ticket_numbers!!} foram fechados e mesclados com <a href="{!!$ticket_link!!}">{!!$ ticket_number!!}</a>.&nbsp;</p><p>Possíveis motivos para mesclar tickets:</p><ul><li>Os tickets estão duplicados.</li><li>Os tickets apresentam&nbsp;o mesmo problema<!-- li--></li><li>Outro membro da sua organização criou um ticket para o mesmo problema</li></ul><p><a href="{!!$system_link!!}">Clique aqui</a> para fazer login em sua conta e verificar seus tickets.</p><p>Atenciosamente,<br><span style="font-size: 0.875rem;">{!!$system_from!!}</span></p>','',1,'2017-01-01 20:20:12','2023-12-09 02:02:35');
